INSERT INTO T_CATEGORY(DESCRIPTION, NAME)  VALUES('Computer', 'Computer');
INSERT INTO T_CATEGORY(DESCRIPTION, NAME)  VALUES('Art', 'Art');
INSERT INTO T_CATEGORY(DESCRIPTION, NAME)  VALUES('Cook', 'Cook');
INSERT INTO T_CATEGORY(DESCRIPTION, NAME)  VALUES('Sport', 'Sport');